July 2024 Release
JeffersonLab/SciOptControlToolkit pull request #11
Opened 2024-07-19 20:25 UTC by armenkasp

# Overall Additions

- [x] Added SAC
- [x] Inference model saving based on average reward increase
- [x] Small bug fixes
- [x] Optimizations
- [x] Inference Actions on Tensorboard

# Benchmark Results:

<img width="547" alt="Screenshot 2024-07-19 at 4 11 35 PM" src="https://github.com/user-attachments/assets/f821fcf4-3948-4d4a-b0ce-5f5747da46ea">
<img width="558" alt="Screenshot 2024-07-19 at 4 11 44 PM" src="https://github.com/user-attachments/assets/654ad350-855f-483e-807b-fa0a205ca55b">
<img width="376" alt="Screenshot 2024-07-19 at 4 11 25 PM" src="https://github.com/user-attachments/assets/774fd527-c2e2-4dd9-a95b-3a23e4ce4e94">

# Unit Tests Results:

<img width="626" alt="Screenshot 2024-07-19 at 2 22 53 PM" src="https://github.com/user-attachments/assets/1c3f5720-2ceb-44b8-82fd-d734b77b961b">
<img width="1123" alt="Screenshot 2024-07-19 at 3 23 41 PM" src="https://github.com/user-attachments/assets/2cbcb7a9-1188-43f5-bd5e-a1952271e2fb">

# Tensorboard Inference Output

<img width="869" alt="image" src="https://github.com/user-attachments/assets/a4b8a227-ba7a-4f47-a72f-88bec532a69e">

2024-08-06 18:43 UTC, Kishanrajput requested changes
I think it looks good overall. Please have a look at the comments below.

2024-08-06 18:43 UTC, Kishanrajput commented on jlab_opt_control/agents/keras_sac.py
> +                                  step=int(self.nactions))
I'm not sure I follow, how can num_actions be 0?

2024-08-06 18:43 UTC, Kishanrajput commented on jlab_opt_control/agents/keras_sac.py
> +                                  step=int(self.nactions))
Should it be 
`self.num_actions == 1:` ?

2024-08-06 18:43 UTC, Kishanrajput commented on jlab_opt_control/agents/keras_ddpg.py
> +            if self.num_actions == 0:
Same comment as SAC, `self.num_actions == 0:` --> should it be `self.num_actions == 1:`?

2024-08-06 18:43 UTC, Kishanrajput commented on jlab_opt_control/agents/keras_td3.py
> +            if self.num_actions == 0:
`self.num_actions == 0:` --> should it be `self.num_actions == 1:`?

2024-08-08 18:02 UTC, armenkasp commented on jlab_opt_control/agents/keras_td3.py
> +            if self.num_actions == 0:
Changed the code in the agents to not be linked to size of action space for tensorboard logging!

2024-08-09 21:09 UTC, Kishanrajput approved these changes
Thank you for addressing my comments. I ran the "tests" and everything pass. However, I do not think we have proper unit tests, perhaps something to focus in the next release.

2024-08-09 21:09 UTC, merged