March 2024 Release
JeffersonLab/SciOptControlToolkit pull request #2
Opened 2024-03-28 19:09 UTC by armenkasp

Please see issue and new Wiki for documentation and details.

https://github.com/JeffersonLab/SciOptControlToolkit/issues/1

https://github.com/JeffersonLab/SciOptControlToolkit/wiki

2024-04-02 14:09 UTC, Kishanrajput commented on README.md
Curious to understand the reason for python version downgrade.

2024-04-02 14:10 UTC, Kishanrajput commented on env.yaml
We should have version number for all the python packages. As I understand it, without version number by default pip installs the latest version and it can break the code.

2024-04-02 14:34 UTC, armenkasp commented on env.yaml
Added dependency versions in the env.yaml

2024-04-02 14:34 UTC, armenkasp commented on README.md
This was done to make codebase more compatible with another Labs systems

2024-04-04 14:28 UTC, Kishanrajput requested changes
@armenkasp Let's see if you can see the comments now.

2024-04-04 14:28 UTC, Kishanrajput commented on jlab_opt_control/models/actor_fcnn.py
@armenkasp, I noticed that you have cfg files for the actor and critic models but you are not using them. We should avoid hard coded architectures. Can you read the number of nodes, activation etc from the config and used them for these models?

2024-04-04 14:28 UTC, Kishanrajput commented on jlab_opt_control/models/critic_fcnn.py
@armenkasp, same comment as above for both actor and critic fcnn models.

2024-04-04 14:32 UTC, armenkasp commented on jlab_opt_control/models/actor_fcnn.py
Now you can read in from the config number of hidden layers and pass an array with the number of nodes in those hidden layers!

![image](https://github.com/JeffersonLab/SciOptControlToolkit/assets/155679987/8ce42cab-3929-486d-9d16-d5a611a1e236)

2024-04-04 14:32 UTC, armenkasp commented on jlab_opt_control/models/critic_fcnn.py
Done for both the actor and critic FCNN models

2024-04-04 14:43 UTC, Kishanrajput commented on jlab_opt_control/models/actor_fcnn.py
Nice, can we also make activation function part of config as well and not hard-coded. Also, let's add try except to make error messages more meaningful for the number of layers vs nodes in the layer config parameters.

2024-04-04 14:49 UTC, armenkasp commented
Added error if mismatch between model number of hidden layers and provided number of values of the nodes in the hidden layers:

![image](https://github.com/JeffersonLab/SciOptControlToolkit/assets/155679987/5668a76a-ee25-4d35-8037-eba9a023bd37)

2024-04-04 14:50 UTC, armenkasp commented
Added activation function selection in the configuration of the actor/critic FCNN models.

![image](https://github.com/JeffersonLab/SciOptControlToolkit/assets/155679987/931c6d40-e8d1-4cb9-a7e9-07b3e2a7d454)

2024-04-05 14:45 UTC, Kishanrajput approved these changes
Seems good to go. Great job! Just one comment I have that should be addressed in upcoming releases. The output scaling of the actor model is particularly designed for tanh output activation and it will not work if someone uses other activation function. This should be clearly mentioned that we only support 'tanh' for the actor output for now and add a check in the model building as well.

2024-04-05 19:44 UTC, merged